[package]
name = "qrfs_fsck"
version = "0.1.0"
edition = "2024"

[dependencies]
qrfs_lib = { version = "0.1.0", path = "../qrfs_lib" }
clap = { version = "4.4", features = ["derive"] }
rpassword = "7.0"
anyhow = "1.0"
bincode = "1.3"
colored = "2.0" # Para imprimir OK en verde y ERROR en rojo